# Rezolvarea sistemelor liniare determinate.
# Sisteme triunghiulare.
# Eliminarea gaussiană.


### 2.2.1 Rezolvarea sistemelor triunghiulare

Algoritmii pentru rezolvarea sistemelor triunghiulare sunt foarte
simpli, întrucât necunoscutele pot fi calculate, într-o ordine definită,
prin substituţie numerică directă. Considerăm, mai întâi, un sistem
inferior triunghiular $$Lx = b,$$ unde $L \in {\mathbb R}^{n\times n}$,
cu $l_{ij} = 0$ pentru $i<j$, $l_{ii} \ne 0$, $i=1:n$, şi
$b \in {\mathbb R}^n$. Prima ecuaţie este $$l_{11} x_1 = b_1,$$ de unde
$$x_1 = b_1 / l_{11}.
\label{eq:l1}$$ În general, dacă ştim $x_1$, $x_2$, ..., $x_{i-1}$,
putem rezolva ecuaţia $i$
$$\sum_{j=1}^{i-1}{l_{ij} x_j} + l_{ii} x_i = b_i$$ şi obţinem
$$x_i = \left( b_i - \sum_{k=1}^{i-1}{l_{ij} x_j} \right) / l_{ii}.
\label{eq:li}$$

ALGORITM 2.1 _(S\_INF\_TR)_ (Dată o matrice $L\in {\mathbb R}^{n\times n}$,
nesingulară, inferior triunghiulară şi un vector $b\in{\mathbb R}^n$,
algoritmul calculează soluţia $x$ a sistemului $Lx=b$.)

1. **pentru** $i=1:n$<br>
&emsp;&emsp;1. $s \leftarrow b_i$<br>
&emsp;&emsp;2. **pentru** $j=1:i-1$<br>
&emsp;&emsp;&emsp;&emsp;1. $s \leftarrow s - l_{ij} x_j$<br>
&emsp;&emsp;3. $x_i \leftarrow s/l_{ii}$
 


Acest algoritm necesită $N_{S\_INF\_TR}\approx n^2$ flopi şi
$M_{S\_INF\_TR}\approx n^2/2$ locaţii de memorie. Dacă vectorul $b$ nu
mai este necesar, soluţia $x$ poate suprascrie vectorul $b$ pe măsură ce
este calculată.


In [1]:
import numpy as np
#Algoritm s_inf_tr
def s_inf_tr(A,b):
    n = A.shape[0]
    x = np.zeros((n,1))
    for i in range(n):
        s = b[i]
        for j in range(i):
            s = s - (A[i][j] * x[j])
        x[i] = s/A[i][i]
    return x

#Verificare
n = 25
A = np.random.rand(n,n)
A = np.tril(A) #matrice inferior triunghiulara
b = np.random.rand(n,1)
# eroare = ||b-Ax||/||b||
eroare = np.linalg.norm(b-np.matmul(A,s_inf_tr(A,b)),2)/np.linalg.norm(b,2)
if eroare < 1E-4:
    print('Corect!')
else:
    print('Gresit!!')
print('eroare : ',eroare)

Corect!
eroare :  6.733577917790594e-13


ALGORITM 2.2 _(S\_SUP\_TR)_ (Dată o matrice $U \in {\mathbb R}^{n \times n}$,
superior triunghiulară, nesingulară şi un vector $b\in {\mathbb R}^n$,
acest algoritm calculează soluţia $x$ a sistemului $Ux=b$.)

1. **pentru** $i=n:-1:1$<br>
&emsp;&emsp;1. $s \leftarrow b_i$<br>
&emsp;&emsp;2. **pentru** $j=i+1:n$<br>
&emsp;&emsp;&emsp;&emsp;1. $s \leftarrow s-u_{ij}x_j$<br>
&emsp;&emsp;3. $x_i \leftarrow s/u_{ii}$<br>
Ca şi în cazul inferior triunghiular, efortul de calcul este dat de
$N_{S\_SUP\_TR}=n^2$ flopi şi memoria necesară este
$M_{S\_SUP\_TR}\approx n^2/2$ locaţii.

In [2]:
def s_sup_tr(A,b):
    n = A.shape[0]
    x = np.zeros((n,1))
    for i in range(n-1,-1,-1):
        s = b[i];
        for j in range(i+1,n):
            s = s - A[i][j] * x[j]
        x[i] = s/A[i][i]
    return x

#Verificare
n = 25
A = np.random.rand(n,n)
A = np.triu(A) #matrice superior triunghiulară
b = np.random.rand(n,1) 
# eroare = ||b-Ax||/||b||
eroare = np.linalg.norm(b-np.matmul(A,s_sup_tr(A,b)),2)/np.linalg.norm(b,2)
if eroare < 1E-4:
    print('Corect!')
else:
    print('Gresit!!')
print('eroare : ',eroare)

Corect!
eroare :  3.46371016155987e-09


### 2.3 Eliminarea Gaussiană

Eliminarea gaussiană este o tehnică pentru reducerea sistemului $Ax=b$
la un sistem superior triunghiular echivalent $$MAx=Mb,$$ i.e. cu
matricea $U=MA$ superior triunghiulară. Matricea de transformare $M$
este o matrice inferior triunghiulară unitară obţinută ca o secvenţă
(produs) de transformări (matrice) inferior triunghiulare elementare
$$M = M_{n-1} M_{n-2} \ldots M_1.$$ O matrice inferior triunghiulară
elementară (ITE) de ordin $n$ şi indice $k$ este o matrice de forma
$$M_k = I_n - m_k e_k^T,\quad
  m_k=[\underbrace{0 \ \ldots \ 0}_{k} \ \mu_{k+1,k} \ \ldots \ \mu_{nk}]^T.$$

ALGORITM 2.3 _\(G)_ (Dată o matrice $A\in {\mathbb R}^{n\times n}$ cu submatricele lider
principale $A^{[k]}$, $k=1:n-1$, nesingulare, acest algoritm suprascrie
triunghiul superior al lui $A$, inclusiv diagonala, cu matricea superior
triunghiulară $U = M_{n-1} M_{n-2} \ldots M_1 A$. Triunghiul inferior al
lui $A$ este suprascris cu multiplicatorii gaussieni $\mu_{ik}$ care
definesc matricele ITE $M_k$, $k=1:n-1$.)

1. **pentru** $k=1:n-1$<br>
&emsp;&emsp;1. **pentru** $i=k+1:n$<br>
&emsp;&emsp;&emsp;&emsp;1. $a_{ik} \leftarrow \mu_{ik} = a_{ik}/a_{kk}$<br>
&emsp;&emsp;2. **pentru** $i=k+1:n$<br>
&emsp;&emsp;&emsp;&emsp;1. **pentru** $j=k+1:n$<br>
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;1. $a_{ij} \leftarrow a_{ij} - \mu_{ik} a_{kj}$


Efortul de calcul este $N_G\approx \frac{2n^3}{3}$ flopi, în timp ce
memoria necesară este $M_G = n^2$ locaţii.

_Observaţie._ Nesingularitatea submatricelor lider principale ale matricei $A$ nu este
o condiţie necesară pentru existenţa şi unicitatea soluţiei unui sistem
de forma $Ax=b$. Pentru a elimina această condiţie vom introduce
pivotarea.

In [34]:
#Alg G
def G(A):
    n = A.shape[0]
    for k in range(n-1):
        for i in range(k+1,n):
            A[i][k] = A[i][k]/A[k][k]
            for j in range(k+1,n):
                A[i][j] = A[i][j] - (A[i][k]*A[k][j])
    return A
# Testare
n = 5
A = np.random.rand(5,5)
print(A)
print('\n')
print(G(A))

[[0.8504 0.9802 0.0595 0.9238 0.5189]
 [0.2429 0.9886 0.5901 0.5773 0.7039]
 [0.5701 0.9483 0.8357 0.2326 0.3222]
 [0.2249 0.6157 0.5106 0.8858 0.0295]
 [0.4497 0.9273 0.498  0.527  0.7571]]


[[ 0.8504  0.9802  0.0595  0.9238  0.5189]
 [ 0.2857  0.7086  0.5731  0.3135  0.5557]
 [ 0.6703  0.411   0.5603 -0.5155 -0.254 ]
 [ 0.2644  0.5032  0.3685  0.6738 -0.2937]
 [ 0.5288  0.5771  0.2423 -0.0261  0.2159]]


### Pivotare parţială
Pivotarea parţială are loc prin permutarea numai a liniilor. La pasul
$k$ al algoritmului G se aduce în poziţia $(k,k)$ a pivotului cel mai
mare element în modul dintre elementele subdiagonale din coloana $k$,
fie acesta $a_{i_k k}\ne 0$, prin permutarea liniilor $k$ şi $i_k$.
Acest lucru este echivalent cu premultiplicarea matricei $A$ cu matricea
de permutare elementară $P_{i_k k}\stackrel{\rm not}{=}P_k$, astfel
încât pasul $k$ realizează $$A \leftarrow M_k P_k A,$$ iar întregul
algoritm realizează triangularizarea matricii $A$ prin secvenţa
$$A\leftarrow U= M_{n-1} P_{n-1} M_{n-2} P_{n-2} \ldots M_1 P_1 A.$$

ALGORITM 2.4 _(GPP -- eliminarea gaussiană cu pivotare parţială)_ (Dată o matrice
$A\in{\mathbb R}^{n\times n}$, algoritmul suprascrie triunghiul
superior al lui $A$ cu matricea superior triunghiulară
$U= M_{n-1} P_{n-1} \ldots M_1 P_1 A$. Triunghiul strict inferior al
lui $A$ este suprascris de multiplicatorii gaussieni $\mu_{ik}$ ce
definesc matricele ITE $M_k$, $k=1:n-1$, iar întregii $i_k$, definind
permutările de linii, sunt memoraţi într-un vector $p$, astfel încât
$p(k)=i_k$, pentru $k=1:n-1$.)

1. **pentru** $k=1:n-1$<br>
&emsp;&emsp;1. Se determină primul $i_k \in k:n$ astfel încât<br>
&emsp;&emsp;&emsp;&emsp;$|a_{i_k k}|=\max_{i=k:n} |a_{ik}|$.<br>
&emsp;&emsp;2. $p(k) \leftarrow i_k$<br>
&emsp;&emsp;3. **pentru** $j=k:n$<br>
&emsp;&emsp;&emsp;&emsp;1. $a_{kj} \leftrightarrow a_{i_k j}$<br>
&emsp;&emsp;4. **pentru** $i=k+1:n$<br>
&emsp;&emsp;&emsp;&emsp;1. $a_{ik} \leftarrow \mu_{ik} = a_{ik}/a_{kk}$<br>
&emsp;&emsp;5. **pentru** $i=k+1:n$<br>
&emsp;&emsp;&emsp;&emsp;1. **pentru** $j=k+1:n$<br>
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;1. $a_{ij} \leftarrow a_{ij}-\mu_{ik}a_{kj}$<br>

Complexitatea algoritmului GPP este aceeaşi cu cea a algoritmului G.

In [3]:
def GPP(A):
    n = A.shape[0]
    p = np.zeros((n-1,1),dtype=np.uint16)
    for k in range(n-1):
        p[k] = np.argmax(np.absolute(A[k:, k])) + k
        p_k = p[k].item()
        for j in range(k,n):
            A[k][j], A[p_k][j] = A[p_k][j], A[k][j]
        for i in range(k+1,n):
            A[i][k] = A[i][k]/A[k][k]
        for i in range(k+1,n):
            for j in range(k+1,n):
                A[i][j] = A[i][j] - A[i][k]*A[k][j]
    return (A, p)

### Pivotare completă
Proprietăţi numerice mai bune se obţin dacă pivotul de la pasul $k$ se
alege drept cel mai mare element în modul dintre elementele $a_{ij}$, cu
$i=k:n$, $j=k:n$. Acest cel mai mare element în modul, fie el
$a_{i_k j_k}$, este adus în poziţia $(k,k)$ a pivotului prin permutarea
liniilor $k$ şi $i_k$ şi a coloanelor $k$ şi $j_k$. Acest lucru este
echivalent cu premultiplicarea matricei $A$ cu matricea de permutare
elementară $P_{i_k k}\stackrel{\rm not}{=}P_k$ şi cu postmultiplicarea
cu matricea de permutare elementară $Q_{j_k k}\stackrel{\rm not}{=}Q_k$,
astfel încât pasul $k$ realizează $$A \leftarrow M_k P_k A Q_k,$$ iar
întregul algoritm realizează triangularizarea matricii $A$ prin secvenţa
$$A\leftarrow U=M_{n-1}P_{n-1}\ldots M_2P_2M_1P_1AQ_1Q_2\cdots Q_{n-1}.$$

ALGORITM 2.5 _(GPC -- eliminarea gaussiană cu pivotare completă)_ (Dată a matrice
$A \in {\mathbb R}^{n \times n}$, acest algoritm suprascrie triunghiul
superior al lui $A$ cu matricea superior triunghiulară $U$. Triunghiul
strict inferior al lui $A$ este suprascris cu multiplicatorii
gaussieni $\mu_{ik}$, $k=1:n-1$, $i=k+1:n$. Întregii $i_k$ şi $j_k$,
ce definesc permutările de linii, respectiv coloane, sunt memoraţi în
doi vectori $p$ şi $q$, astfel încât $p(k) = i_k$ şi $q(k) = j_k$,
pentru $k=1:n-1$.)

1. **pentru** $k=1:n-1$<br>
&emsp;&emsp;1. Se determină $i_k\in k:n$ şi $j_k\in k:n$ astfel încât<br>
&emsp;&emsp;&emsp;&emsp;$|a_{i_k j_k}|=\max_{i=k:n,j=k:n} |a_{ij}|$.<br>
&emsp;&emsp;2. $p(k) \leftarrow i_k$<br>
&emsp;&emsp;3. $q(k) \leftarrow j_k$<br>
&emsp;&emsp;4. **pentru** $j=k:n$<br>
&emsp;&emsp;&emsp;&emsp;1. $a_{kj} \leftrightarrow a_{i_k j}$<br>
&emsp;&emsp;5. **pentru** $i=1:n$<br>
&emsp;&emsp;&emsp;&emsp;1. $a_{ik} \leftrightarrow a_{i j_k}$<br>
&emsp;&emsp;6. **pentru** $i=k+1:n$<br>
&emsp;&emsp;&emsp;&emsp;1. $a_{ik} \leftarrow \mu_{ik} = a_{ik}/a_{kk}$<br>
&emsp;&emsp;7. **pentru** $i=k+1:n$<br>
&emsp;&emsp;&emsp;&emsp;1. **pentru** $j=k+1:n$<br>
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;1. $a_{ij} \leftarrow a_{ij}-\mu_{ik} a_{kj}$

Complexitatea algoritmului GPC este aceeaşi cu cea a algoritmului G.

In [4]:
def GPC(A):
    n = A.shape[0]
    p = np.zeros((n-1,1),dtype=np.uint16)
    q = np.zeros((n-1,1),dtype=np.uint16)
    for k in range(n-1):
        max_ind = np.argmax(np.absolute(A[k:, k:]))
        p[k] = int(max_ind/(n-k)) + k
        q[k] = max_ind%(n-k) + k
        p_k = p[k].item()
        q_k = q[k].item()
        
        for j in range(k,n):
            A[k][j], A[p_k][j] = A[p_k][j], A[k][j]
        for i in range(n):
            A[i][k], A[i][q_k] = A[i][q_k], A[i][k]
        for i in range(k+1,n):
            A[i][k] = A[i][k]/A[k][k]
        for i in range(k+1,n):
            for j in range(k+1,n):
                A[i][j] = A[i][j] - A[i][k]*A[k][j]
    return (A, p, q)

### 2.4 Rezolvarea sistemelor liniare determinate
Considerăm sistemul liniar $Ax=b$, cu $A$ nesingulară. Evident, sistemul
$Ax=b$ este echivalent cu sistemul
$$M_{n-1}P_{n-1}\ldots M_1 P_1 A x=M_{n-1}P_{n-1}\ldots M_1 P_1 b,$$
unde $M_k$, $P_k$ sunt matricele utilizate de GPP, i.e. cu sistemul
superior triunghiular $$Ux=M_{n-1}P_{n-1}\ldots M_1 P_1 b,$$ Deci,
pentru a rezolva $Ax= b$, trebuie să calculăm vectorul
$$b \leftarrow d = M_{n-1} P_{n-1} \ldots M_1 P_1 b,$$ folosind
următoarea schemă:

1. **pentru** $k=1:n-1$<br>
&emsp;&emsp;1. $b \leftarrow P_k b$<br>
&emsp;&emsp;2. $b \leftarrow M_k b$.<br>

În cazul utilizării algoritmului GPC sistemul $Ax = b$ este echivalent
cu sistemul
$$M_{n-1}P_{n-1}\ldots M_1 P_1 A Q_1\ldots Q_{n-1} Q_{n-1}\ldots Q_1 x
=  M_{n-1}P_{n-1}\ldots M_1 P_1 b.$$ Notând
$$Q_{n-1} \ldots Q_1 x = y,$$ rezultă că $y$ poate fi calculat ca
soluţie a sistemului superior triunghiular $Uy = d,$ unde
$d=M_{n-1}P_{n-1}\ldots M_1 P_1 b$. Din expresia lui $y$ avem
$$x = Q_1 Q_2 \ldots Q_{n-1}y$$ care poate fi calculat cu schema

1. $x\leftarrow y$<br>
2. **pentru** $k=n-1:-1:1$<br>
&emsp;&emsp;1. $x\leftarrow Q_k x.$<br>


ALGORITM 2.6
_(SL\_GPP -- Rezolvarea sistemelor liniare cu GPP)_ (Dată o matrice
nesingulară $A\in{\mathbb R}^{n\times n}$ şi un vector
$b\in {\mathbb R}^n$, acest algoritm calculează soluţia
$x\in{\mathbb R}^n$ a sistemului liniar $Ax=b$, folosind eliminarea
gaussiană cu pivotare parţială.)

1. $[\,M,U,p\,]=\,$GPP$(A)$<br>
2. **pentru** $k=1:n-1$<br>
&emsp;&emsp;1. $b_k \leftrightarrow b_{p(k)}$<br>
&emsp;&emsp;2. **pentru** $i=k+1:n$<br>
&emsp;&emsp;&emsp;&emsp;1. $b_i \leftarrow b_i - \mu_{ik} b_k$<br>
3. $x =\,$S\_SUP\_TR$(U,b)$<br><br>
Complexitatea algoritmului este dată de
$$N_{SL\_GPP} = N_{GPP}+\sum_{k=1}^{n-1}{2(n-k)}+N_{S\_SUP\_TR} \approx
\frac{2n^3}{3} + n^2 + n^2 \approx \frac{2n^3}{3} \approx N_{GPP}.$$

In [5]:
def SL_GPP(A,b):
    n = A.shape[0]
    (A, p) = GPP(A)
    M = np.tril(A)
    U = np.triu(A)
    for k in range(n-1):
        p_k = p[k].item()
        b[[k, p_k]] = b[[p_k, k]]
        for i in range(k+1,n):
            b[i] = b[i] - M[i][k]*b[k]
    x = s_sup_tr(U,b)
    return x 

#Testare 
n = 50
A = np.random.rand(n,n)
b = np.random.rand(n,1)
A_cl = A.copy() #lucram cu referinta, copiem originalul
b_cl = b.copy()
# eroare = ||b-Ax||/||b||
eroare = np.linalg.norm(b_cl-np.matmul(A_cl,SL_GPP(A,b)),2)/np.linalg.norm(b_cl,2)
if eroare < 1E-4:
    print('Corect!')
else:
    print('Gresit!')
print('eroare : ',eroare)

Corect!
eroare :  4.8965039512584184e-15


ALGORITM 2.7 _(SL\_GPC -- rezolvarea sistemelor liniare cu GPC)_ (Dată o matrice
nesingulară $A\in{\mathbb R}^{n\times n}$ şi un vector
$b \in {\mathbb R}^n$, acest algoritm calculează soluţia
$x \in {\mathbb R}^n$ a sistemului liniar $Ax=b$, folosind eliminarea
gaussiană cu pivotare completă.)

1. $[\,M,U,p,q\,]=\,$GPC$(A)$<br>
2. **pentru** $k=1:n-1$<br>
&emsp;&emsp;1. $b_k \leftrightarrow b_{p(k)}$<br>
&emsp;&emsp;2. **pentru** $i=k+1:n$<br>
&emsp;&emsp;&emsp;&emsp;1. $b_i \leftarrow b_i-\mu_{ik} b_k$<br>
3. $x =\,$S\_SUP\_TR$(U,b)$<br>
4. **pentru** $k=n-1:-1:1$<br>
&emsp;&emsp;1. $x_k \leftrightarrow x_{q(k)}$<br>

In [6]:
#Rezolvare de sisteme liniare cu GPC
def SL_GPC(A,b):
    (A, p, q) = GPC(A)
    n = A.shape[0]
    M = np.tril(A)
    U = np.triu(A)
    for k in range(n-1):
        p_k = p[k].item()
        b[[k, p_k]] = b[[p_k, k]]
        for i in range(k+1,n):
            b[i] = b[i] - M[i][k]*b[k]
    x = s_sup_tr(U,b)
    for k in range(n-2,-1,-1):
        q_k = q[k].item()
        x[[k, q_k]] = x[[q_k, k]]
    return x

#Verificare
n = 50
A = np.random.rand(n,n)
b = np.random.rand(n,1)
A_cl = A.copy() #lucram cu referinta, copiem originalul
b_cl = b.copy()
# eroare = ||b-Ax||/||b||
eroare = np.linalg.norm(b_cl-np.matmul(A_cl,SL_GPC(A,b)),2)/np.linalg.norm(b_cl,2)
if eroare < 1E-4:
    print('Corect!')
else:
    print('Gresit!')
print('eroare : ',eroare)

Corect!
eroare :  7.774006188059314e-16


# 2.5.2 B. Acasă

In [7]:
def s_sup_bidiag(A,b):
    n = A.shape[0]
    x = np.zeros((n,1))
    x[n-1] = b[n-1]/A[n-1][n-1]
    for i in range(n-2,-1,-1):
        s = b[i];
        s = s - A[i][i+1] * x[i+1]
        x[i] = s/A[i][i]
    return x

n = 200
A = np.random.rand(n,n)
A = np.triu(A)-np.triu(A,2) #generam matricea superior bidiagonala
b = np.random.rand(n,1)
#eroare = ||b-Ax||/||b||
eroare = np.linalg.norm(b - np.matmul(A,s_sup_bidiag(A,b)),2)/np.linalg.norm(b)
if eroare < 1E-4:
    print('Corect!')
else:
    print('Gresit!!')
print('eroare : ',eroare)

Corect!
eroare :  1.33955560866472e-07


In [8]:
def s_inf_bidiag(A,b):
    n = A.shape[0]
    x = np.zeros((n,1))
    x[0] = b[0]/A[0][0]
    for i in range(1,n):
        s = b[i]
        s = s - (A[i][i-1] * x[i-1])
        x[i] = s/A[i][i]
    return x
    
n = 200
A = np.random.rand(n,n)
A = np.tril(A)-np.tril(A,-2) #generam matricea inferior bidiagonala
b = np.random.rand(n,1)
#eroare = ||b-Ax||/||b||
eroare = np.linalg.norm(b - np.matmul(A,s_inf_bidiag(A,b)),2)/np.linalg.norm(b,2)
if eroare < 1E-4:
    print('Corect!')
else:
    print('Gresit!')
print('eroare : ',eroare)

Corect!
eroare :  2.3809980081564257e-08


In [11]:
# Testare GPC pe coeficienti mai mari si numar mare de ecuatii
n = 200;
#Observatie : pentru n>200 poate dura putin mai mult rezolvarea sistemului
A = 100*np.random.rand(n,n)
b = np.random.rand(n,1)
A_cl = A.copy() #lucram cu referinta
b_cl = b.copy()
eroare = np.linalg.norm(b_cl-np.matmul(A_cl,SL_GPC(A,b)),2)/np.linalg.norm(b_cl,2)
if eroare < 1E-4:
    print('Corect!')
else:
    print('Gresit!')
print('eroare : ',eroare)

Corect!
eroare :  7.05555174562329e-13


# Animaţii

## 1. Algoritm G

In [ ]:
#Alg G
import time
import numpy as np
from IPython.display import clear_output
def afisez_matrice_color(A,lin,col,k):
    n = A.shape[0]
    clear_output(wait=True)
    for i in range(n):
        for j in range(n):
            #formatare output
            if(A[i][j] >= 0):
                cell_str = str(' '+str('{:2.3f}'.format(round(A[i][j],3)+0)))
            else:
                cell_str = str('{:2.3f}'.format(round(A[i][j],3)+0))
            if(i<lin):
                if(i<=k+1):
                    if(j<i):
                        print("\x1b[33m",cell_str,"\x1b[m",end='')
                    else:
                        print("\x1b[32m",cell_str,"\x1b[m",end='')
                else:
                    if(j<=k):
                        print("\x1b[33m",cell_str,"\x1b[m",end='')
                    else:
                        print("\x1b[35m",cell_str,"\x1b[m",end='')
            elif(i==lin):
                if(j==col):
                    print("\x1b[44m",cell_str,"\x1b[m",end='')
                elif(j<=k):
                    print("\x1b[33m",cell_str,"\x1b[m",end='')
                elif(j<col and lin==k+1):
                    print("\x1b[32m",cell_str,"\x1b[m",end='')
                elif(j<col):
                    print("\x1b[35m",cell_str,"\x1b[m",end='')
                else:
                    print("\x1b",cell_str,"\x1b",end='')
            else:
                if(j<k):
                    print("\x1b[33m",cell_str,"\x1b[m",end='')
                else:
                    print("\x1b",cell_str,"\x1b",end='')
        if(i==k): #afisam sageata
            print(' ---',end='')
        elif(i>k and i<lin):
            print('   |',end='')
        elif(i==lin):
            print(' <-|',end='')
        print('\n',end='')
    try:
        time.sleep(timp_tranzitie)
    except KeyboardInterrupt:
        pass
    
                

def G_animat(A,timp_tranzitie):
    globals().update(timp_tranzitie=timp_tranzitie)
    n = A.shape[0]
    A_cl = A.copy()
    matrice_coef = np.zeros((n,n))
    for k in range(n-1):
        for i in range(k+1,n):
            A[i][k] = A[i][k]/A[k][k]
            for j in range(k+1,n):
                A[i][j] = A[i][j] - (A[i][k]*A[k][j])
                afisez_matrice_color(A,i,j,k)
    afisez_matrice_color(A,n,n,n)
    return A

#Testare
A = np.random.randint(1,50,size=(5,5))
A = A.astype('float64')/100
#rotunjim afisarea numerelor la 4 zecimale
np.set_printoptions(precision=4)

timp_tranzitie=10;
A_rezultat = G_animat(A,timp_tranzitie)
print('\nMatrice finala:')
print(A_rezultat)

  0.060   0.110   0.100   0.320   0.370  ---
  5.667  -0.553  -0.447  -1.533  -2.087    |
  0.667  -0.023   0.023   0.157   0.103  <-|
  0.340   0.440   0.190   0.380   0.270 
  0.300   0.290   0.490   0.080   0.260 


## 2. Algoritm GPP

In [ ]:
def interschimb_linii_color(A,orig_index,pivot_index,
                            pivot_j,lim_submatrice,trecPeste=False):
    n = A.shape[0]
    clear_output(wait=True)
    if(orig_index != pivot_index):
        trecPeste = False
    for i in range(n):
        for j in range(n):
            #formatare output
            if(A[i][j] >= 0):
                cell_str = str(' '+str('{:.2f}'.format(round(A[i][j],2)+0)))
            else:
                cell_str = str('{:.2f}'.format(round(A[i][j],2)+0))
        
            if(i == pivot_index and j >= lim_submatrice):
                if(j == pivot_j):
                    print("\x1b[43m",cell_str,"\x1b[m",end='')
                else:
                    print("\x1b[34m",cell_str,"\x1b[m",end='')
            elif(i == orig_index and j>= lim_submatrice):
                print("\x1b[31m",cell_str,"\x1b[0m",end='')
            elif(i>=lim_submatrice and j>=lim_submatrice):
                print("\x1b[32m",cell_str,"\x1b[0m",end='')
            elif(i>j):
                print("\x1b[33m",cell_str,"\x1b[0m",end='')
            else:
                print("\x1b", cell_str,"\x1b",end='')
        print('\n',end='')
    try:
        if trecPeste==True:
            raise KeyboardInterrupt
        time.sleep(timp_tranzitie)
    except KeyboardInterrupt:
        pass
        
def GPP_animat(A, timp_tranizitie):
    globals().update(timp_tranzitie=timp_tranzitie)
    n = A.shape[0]
    p = np.zeros((n-1,1),dtype=np.uint16)
    for k in range(n-1):
        p[k] = np.argmax(np.absolute(A[k:, k])) + k
        p_k = p[k].item()
        
        interschimb_linii_color(A,k,p_k,k,k)
        
        for j in range(k,n):
            A[k][j], A[p_k][j] = A[p_k][j], A[k][j]
            
        interschimb_linii_color(A,p_k,k,k,k,True)
            
        for i in range(k+1,n):
            A[i][k] = A[i][k]/A[k][k]
        for i in range(k+1,n):
            for j in range(k+1,n):
                A[i][j] = A[i][j] - A[i][k]*A[k][j]
    interschimb_linii_color(A,-1,-1,-1,n)
    return(A, p)
    
    
    
A = np.random.randint(1,5,size=(6,6))
A = A.astype('float64')
timp_tranzitie = 10
(A_fin, p) = GPP_animat(A,timp_tranzitie)

print('Matrice finala : ')
print(A_fin)
print('Vector permutare : ')
print(p)


## 3. Algoritm GPC

In [ ]:

def interschimb_color_gpc(A,orig_index,pivot_index,pivot_i,pivot_j,
                          lim_submatrice,coloana=False,trecPeste=False):
    n = A.shape[0]
    clear_output(wait=True)
    if(orig_index != pivot_index):
        trecPeste = False
    for i in range(n):
        for j in range(n):
            if(A[i][j] >= 0):
                cell_str = str(' '+str('{:.3f}'.format(round(A[i][j],3)+0)))
            else:
                cell_str = str('{:.3f}'.format(round(A[i][j],3)+0))
        
            if(i == pivot_i and j == pivot_j):
                print("\x1b[43m",cell_str,"\x1b[m",end='')
            elif(i == orig_index and j>=lim_submatrice and coloana == False):
                print("\x1b[34m",cell_str,"\x1b[0m",end='')
            elif(i == pivot_index and j>=lim_submatrice and coloana == False):
                print("\x1b[31m",cell_str,"\x1b[0m",end='')
            elif(j == orig_index and coloana == True):
                print("\x1b[34m",cell_str,"\x1b[0m",end='')
            elif(j == pivot_index and coloana == True):
                print("\x1b[31m",cell_str,"\x1b[0m",end='')
            elif(i>=lim_submatrice and j>=lim_submatrice):
                print("\x1b[32m",cell_str,"\x1b[0m",end='')
            elif(i>j):
                print("\x1b[33m",cell_str,"\x1b[0m",end='')
            else:
                print("\x1b", cell_str,"\x1b",end='')
        print('\n',end='')
    try:
        if trecPeste==True:
            raise KeyboardInterrupt
        time.sleep(timp_tranzitie)
    except KeyboardInterrupt:
        pass
            
        
#GPC
def GPC_animat(A, timp_tranzitie):
    globals().update(timp_tranzitie=timp_tranzitie)
    n = A.shape[0]
    p = np.zeros((n-1,1),dtype=np.uint16)
    q = np.zeros((n-1,1),dtype=np.uint16)
    matrice_coef = np.zeros((n,n))
    for k in range(n-1):
        max_ind = np.argmax(np.absolute(A[k:, k:]))
        p[k] = int(max_ind/(n-k)) + k
        q[k] = max_ind%(n-k) + k
        p_k = p[k].item()
        q_k = q[k].item()
        
        interschimb_color_gpc(A,k,p_k,p_k,q_k,k,False)
        for j in range(k,n):
            A[k][j], A[p_k][j] = A[p_k][j], A[k][j]
        interschimb_color_gpc(A,p_k,k,k,q_k,k,False,True)
        
        interschimb_color_gpc(A,k,q_k,k,q_k,k,True)
        for i in range(n):
            A[i][k], A[i][q_k] = A[i][q_k], A[i][k]
        interschimb_color_gpc(A,q_k,k,k,k,k,True,True)
        
        for i in range(k+1,n):
            A[i][k] = A[i][k]/A[k][k]
        for i in range(k+1,n):
            for j in range(k+1,n):
                A[i][j] = A[i][j] - A[i][k]*A[k][j]
    interschimb_color_gpc(A,n,n,n,n,n,True)
    return (A, p, q)

#Testare
np.set_printoptions(precision=4)
    
A = np.random.randint(1,5,size=(6,6))
A = A.astype('float64')
#setare timp tranzitie
timp_tranzitie = 10
(A_fin, p, q) = GPC_animat(A,timp_tranzitie)
print('Rezultat : ')
print(A_fin)
print('Permutari linii : ')
print(p)
print('Permutari coloane : ')
print(q)
